//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladWPF.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public string Number { get; set; }
        public int IDSupplier { get; set; }
        public int IDEmployees { get; set; }
        public int IDStorage { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Users Users { get; set; }
    }
}
