//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkladWPF.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public string Number { get; set; }
        public string Shelf { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int IDStorage { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
